# Generated by Django 4.2 on 2024-03-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Во сколько выполнять')),
                ('action', models.CharField(verbose_name='Действие')),
                ('is_useful', models.BooleanField(default=True, verbose_name='Приятная привычка')),
                ('periodicity', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='daily', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Время выполнения в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Общий доступ')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
