# Generated by Django 4.2 on 2024-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_launch',
            field=models.DateField(blank=True, null=True, verbose_name='предыдущий запуск'),
        ),
    ]
